spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server.codebetterlife.com:30001/project_assistant?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: project-assistant
    password: project-assistant@0318


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false